<a href="https://colab.research.google.com/github/Suraj9989/Python-problem-Analytics-/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Transformation

In [ ]:
import pandas as pd

from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    MinMaxScaler,
    StandardScaler
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:
df = pd.read_csv("/content/employee_productivity_dataset.csv")
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True)

df['Salary'].fillna(df['Salary'].mean(), inplace=True)

df['Hours_Worked_Per_Week'].fillna(
    df['Hours_Worked_Per_Week'].median(),
    inplace=True
)

df['Performance_Score'].fillna(
    df['Performance_Score'].mean(),
    inplace=True
)

df.head()

/tmp/ipykernel_2201/4186724084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_2201/4186724084.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
/tmp/ipykernel_2201/4186724084.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hours_Worked_Per_Week'].fillna(
/tmp/ipykernel_2201/4186724084.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Score'].fillna(

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune

Q2. Label Encoding

Convert these columns into numeric values using Label
Encoding:

Gender

Department

Show the updated columns.

In [ ]:
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])

df['Department'] = LabelEncoder().fit_transform(df['Department'])

df[['Gender', 'Department']]

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

Q3. One-Hot Encoding

Apply One-Hot Encoding on:

Work_Mode

Location

Display the dataset and check how many new columns are created

In [ ]:
df_encoded = pd.get_dummies(
    df,
    columns=['Work_Mode', 'Location'],
    drop_first=False
)

print(df_encoded)

print("New Columns Created:",
      len(df_encoded.columns) - len(df.columns))

    Employee_ID         Name  Department   Age  Gender   Join_Date  \
0          E001  Amit Sharma           2  25.0       1  15-01-2021
1          E002   Riya Patel           1  30.0       0  15-02-2020
2          E003  John Mathew           0  29.0       1  10-03-2022
3          E004  Sneha Joshi           2  28.0       0  22-04-2021
4          E005  Arjun Verma           3  35.0       1  18-05-2020
..          ...          ...         ...   ...     ...         ...
245        E006   Neha Singh           1  27.0       0  01-06-2023
246        E007    Rahul Das           0  40.0       1  07-07-2019
247        E008  Pooja Mehta           3  29.0       0  12-08-2022
248        E009  Sameer Khan           2  31.0       1  30-09-2021
249        E010   Kiran Nair           1  26.0       0  05-10-2023

     Hours_Worked_Per_Week  Projects_Completed  Performance_Score  \
0                     40.0                   5             4.5000
1                     38.0                   4             4.0000
2                     45.0                   6             4.3125
3                     41.0                   5             4.2000
4                     50.0                   7             4.8000
..                     ...                 ...                ...
245                   36.0                   3             3.9000
246                   48.0                   8             4.7000
247                   42.0                   6             4.3000
248                   41.0                   5             4.1000
249                   37.0                   4             4.3125

           Salary  Work_Mode_Hybrid  Work_Mode_Onsite  Work_Mode_Remote  \
0    50000.000000             False             False              True
1    45000.000000              True             False             False
2    60000.000000             False              True             False
3    52000.000000             False             False              True
4    50666.666667              True             False             False
..            ...               ...               ...               ...
245  42000.000000             False             False              True
246  65000.000000             False              True             False
247  48000.000000              True             False             False
248  51000.000000             False             False              True
249  43000.000000             False              True             False

     Location_Bangalore  Location_Delhi  Location_Mumbai  Location_Pune
0                 False           False            False           True
1                 False           False             True          False
2                  True           False            False          False
3                 False            True            False          False
4                 False           False            False           True
..                  ...             ...              ...            ...
245               False           False             True          False
246               False            True            False          False
247                True           False            False          False
248               False           False            False           True
249               False           False             True          False

[250 rows x 17 columns]
New Columns Created: 5

Q4. Normalization (Min-Max Scaling)

Normalize the following columns:

Salary

Hours_Worked_Per_Week

Use MinMaxScaler and display results

In [ ]:
scaler = MinMaxScaler()

df[['Salary_Normalized',
    'Hours_Normalized']] = scaler.fit_transform(
        df[['Salary',
            'Hours_Worked_Per_Week']]
)

print(df[['Salary',
          'Salary_Normalized',
          'Hours_Worked_Per_Week',
          'Hours_Normalized']])

           Salary  Salary_Normalized  Hours_Worked_Per_Week  Hours_Normalized
0    50000.000000           0.347826                   40.0          0.285714
1    45000.000000           0.130435                   38.0          0.142857
2    60000.000000           0.782609                   45.0          0.642857
3    52000.000000           0.434783                   41.0          0.357143
4    50666.666667           0.376812                   50.0          1.000000
..            ...                ...                    ...               ...
245  42000.000000           0.000000                   36.0          0.000000
246  65000.000000           1.000000                   48.0          0.857143
247  48000.000000           0.260870                   42.0          0.428571
248  51000.000000           0.391304                   41.0          0.357143
249  43000.000000           0.043478                   37.0          0.071429

[250 rows x 4 columns]

Q5. Standardization (Scaling)

Apply StandardScaler on:

Age

Projects_Completed

Display the transformed values.

In [ ]:
std_scaler = StandardScaler()

df[['Age_Standardized',
    'Projects_Standardized']] = std_scaler.fit_transform(
        df[['Age',
            'Projects_Completed']]
)

print(df[['Age_Standardized',
          'Projects_Standardized']])

     Age_Standardized  Projects_Standardized
0           -1.172018              -0.211604
1            0.000000              -0.916949
2           -0.234404               0.493742
3           -0.468807              -0.211604
4            1.172018               1.199088
..                ...                    ...
245         -0.703211              -1.622295
246          2.344036               1.904433
247         -0.234404               0.493742
248          0.234404              -0.211604
249         -0.937614              -0.916949

[250 rows x 2 columns]

Q6. Compare Scaling Methods

Apply both:

MinMaxScaler

StandardScaler

On the Salary column.

Show both results side by side.

In [ ]:
salary_minmax = MinMaxScaler()
salary_standard = StandardScaler()

df['Salary_MinMax'] = salary_minmax.fit_transform(
    df[['Salary']]
)

df['Salary_Standard'] = salary_standard.fit_transform(
    df[['Salary']]
)

print(df[['Salary',
          'Salary_MinMax',
          'Salary_Standard']])

           Salary  Salary_MinMax  Salary_Standard
0    50000.000000       0.347826        -0.097451
1    45000.000000       0.130435        -0.828333
2    60000.000000       0.782609         1.364312
3    52000.000000       0.434783         0.194902
4    50666.666667       0.376812         0.000000
..            ...            ...              ...
245  42000.000000       0.000000        -1.266862
246  65000.000000       1.000000         2.095194
247  48000.000000       0.260870        -0.389804
248  51000.000000       0.391304         0.048725
249  43000.000000       0.043478        -1.120685

[250 rows x 3 columns]

Q7. Build Preprocessing Pipeline

Create a pipeline that:

Applies encoding to categorical columns

Applies scaling to numerical columns

Use:

ColumnTransformer

Pipeline

In [ ]:
categorical_cols = [
    'Gender',
    'Department',
    'Work_Mode',
    'Location'
]

numerical_cols = [
    'Age',
    'Salary',
    'Hours_Worked_Per_Week',
    'Projects_Completed',
    'Performance_Score'
]

In [ ]:
preprocessor = ColumnTransformer(

    transformers=[

        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_cols
        ),

        (
            'num',
            StandardScaler(),
            numerical_cols
        )

    ]
)

In [ ]:
pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor)
    ]
)

print(pipeline)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Department',
                                                   'Work_Mode', 'Location']),
                                                 ('num', StandardScaler(),
                                                  ['Age', 'Salary',
                                                   'Hours_Worked_Per_Week',
                                                   'Projects_Completed',
                                                   'Performance_Score'])]))])

Q8. Apply Pipeline

Apply the pipeline on the dataset.

Display:

Transformed dataset

Shape of final dataset

In [ ]:
X_transformed = pipeline.fit_transform(df)

print(X_transformed)

print("Shape of Final Dataset:",
      X_transformed.shape)

[[ 0.          1.          0.         ... -0.4112205  -0.21160368
   0.68522446]
 [ 1.          0.          0.         ... -0.86813216 -0.9169493
  -1.14204076]
 [ 0.          1.          1.         ...  0.73105866  0.49374193
   0.        ]
 ...
 [ 1.          0.          0.         ...  0.04569117  0.49374193
  -0.04568163]
 [ 0.          1.          0.         ... -0.18276466 -0.21160368
  -0.77658772]
 [ 1.          0.          0.         ... -1.09658799 -0.9169493
   0.        ]]
Shape of Final Dataset: (250, 18)

Q9. Conceptual Question

Why is scaling important in Python?

Scaling is important because different features can have different ranges.

Example:

Age = 25

Salary = 50000

Without scaling, Salary dominates Age during model training.

Benefits:

Faster model convergence.

Better model accuracy.

Prevents large-valued features from dominating.

Essential for KNN, SVM, K-Means, PCA, Neural Networks.

Q10. Conceptual Question

Why do we convert categorical data into numerical form?

Machine Learning algorithms perform mathematical  
calculations and cannot directly understand text values.

Example:

Gender

Male

Female

Algorithms cannot process these strings.

After encoding:

Male = 1

Female = 0

Benefits:

Makes data understandable to ML models.

Allows mathematical operations.

Improves model training and prediction.